apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: development
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-demo
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
